//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alfred.Server.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13100")]
        public int WebSocketServerPort {
            get {
                return ((int)(this["WebSocketServerPort"]));
            }
            set {
                this["WebSocketServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nam.kicks-ass.org")]
        public string WebSocketServerHostname {
            get {
                return ((string)(this["WebSocketServerHostname"]));
            }
            set {
                this["WebSocketServerHostname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("api-nam.kicks-ass.org")]
        public string WebApiServerHostname {
            get {
                return ((string)(this["WebApiServerHostname"]));
            }
            set {
                this["WebApiServerHostname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int WebApiServerPort {
            get {
                return ((int)(this["WebApiServerPort"]));
            }
            set {
                this["WebApiServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Home")]
        public string WebsiteName {
            get {
                return ((string)(this["WebsiteName"]));
            }
            set {
                this["WebsiteName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.jazzradio.fr/radio/webradio/jazz")]
        public string JazzRadio {
            get {
                return ((string)(this["JazzRadio"]));
            }
            set {
                this["JazzRadio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.ledjamradio.com/playlist.m3u")]
        public string DjamRadio {
            get {
                return ((string)(this["DjamRadio"]));
            }
            set {
                this["DjamRadio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.di.fm/")]
        public string DIRadio {
            get {
                return ((string)(this["DIRadio"]));
            }
            set {
                this["DIRadio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TBtbmYFodVxjCarqzTjih1k0DAqiu1Bx")]
        public string PushBulletApiKey {
            get {
                return ((string)(this["PushBulletApiKey"]));
            }
            set {
                this["PushBulletApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19850665")]
        public string FreeMobileUser {
            get {
                return ((string)(this["FreeMobileUser"]));
            }
            set {
                this["FreeMobileUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gsoRy0VWBCbK9R")]
        public string FreeMobileKey {
            get {
                return ((string)(this["FreeMobileKey"]));
            }
            set {
                this["FreeMobileKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\guillaume\\Documents\\Projects\\Alfred\\AlfredServer\\Web\\public")]
        public string StaticWebsitepath {
            get {
                return ((string)(this["StaticWebsitepath"]));
            }
            set {
                this["StaticWebsitepath"] = value;
            }
        }
    }
}
