//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alfred.Client.Gui.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AlfredDialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlfredDialog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alfred.Client.Gui.Ressources.AlfredDialog", typeof(AlfredDialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui Maitre !;Que puis-je faire ?;Commandez-moi !;En quoi puis-je être utile ?.
        /// </summary>
        internal static string Alfred_Start {
            get {
                return ResourceManager.GetString("Alfred_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&apos;est toujours un plaisir, monsieur !;A votre service !;C&apos;est un plaisir !;C&apos;est bien la moindre des choses.
        /// </summary>
        internal static string Alfred_StopListening {
            get {
                return ResourceManager.GetString("Alfred_StopListening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyez plus gentil !;Parlez-moi sur un autre ton !;J&apos;ai des émotions, vous savez;Je ne suis pas un jouet.
        /// </summary>
        internal static string Common_Insult {
            get {
                return ResourceManager.GetString("Common_Insult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&apos;est fait;Voilà;Cela vous convient-il ?.
        /// </summary>
        internal static string Common_VolumeDown {
            get {
                return ResourceManager.GetString("Common_VolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&apos;est fait;Voilà;Cela vous convient-il ?.
        /// </summary>
        internal static string Common_VolumeUp {
            get {
                return ResourceManager.GetString("Common_VolumeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout de suite;C&apos;est fait;voilà.
        /// </summary>
        internal static string Device_Allume {
            get {
                return ResourceManager.GetString("Device_Allume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout de suite;C&apos;est fait;voilà.
        /// </summary>
        internal static string Device_AllumeTout {
            get {
                return ResourceManager.GetString("Device_AllumeTout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout de suite;C&apos;est fait;voilà.
        /// </summary>
        internal static string Device_Eteins {
            get {
                return ResourceManager.GetString("Device_Eteins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout de suite;C&apos;est fait;voilà.
        /// </summary>
        internal static string Device_EteinsTout {
            get {
                return ResourceManager.GetString("Device_EteinsTout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&apos;est fait;Voilà;Cela vous convient-il ?.
        /// </summary>
        internal static string Device_TurnDown {
            get {
                return ResourceManager.GetString("Device_TurnDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&apos;est fait;Voilà;Cela vous convient-il ?.
        /// </summary>
        internal static string Device_TurnUp {
            get {
                return ResourceManager.GetString("Device_TurnUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout de suite, monsieur.
        /// </summary>
        internal static string MediaManager_LaunchScenario {
            get {
                return ResourceManager.GetString("MediaManager_LaunchScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout de suite;C&apos;est fait;voilà.
        /// </summary>
        internal static string MediaManager_MusicStop {
            get {
                return ResourceManager.GetString("MediaManager_MusicStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout de suite;C&apos;est fait;voilà.
        /// </summary>
        internal static string MediaManager_PlaylistArtist {
            get {
                return ResourceManager.GetString("MediaManager_PlaylistArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout de suite;C&apos;est fait;voilà.
        /// </summary>
        internal static string MediaManager_PlaylistGenre {
            get {
                return ResourceManager.GetString("MediaManager_PlaylistGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La musique a été ajoutée à la playlist.
        /// </summary>
        internal static string Playlist_AddCurrentMusicToPlaylist {
            get {
                return ResourceManager.GetString("Playlist_AddCurrentMusicToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voilà. Bonne chance, monsieur.
        /// </summary>
        internal static string Scenario_LaunchScenario {
            get {
                return ResourceManager.GetString("Scenario_LaunchScenario", resourceCulture);
            }
        }
    }
}
