#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AlfredApp.Droid.Resource", IsApplication=true)]

namespace AlfredApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f030000
			public const int white = 2130903040;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background_textured_example = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ab_bottom_solid_example = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ab_solid_example = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ab_stacked_solid_example = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ab_texture_tile_example = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ab_transparent_example = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int background = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_cab_done_default_example = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_cab_done_example = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_cab_done_focused_example = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btn_cab_done_pressed_example = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int cab_background_bottom_example = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int cab_background_top_example = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int connected = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int djamradio = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_action_next_item = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_action_pause = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_action_play = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_action_previous_item = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Icon = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int list_focused_example = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int list_pressed_example = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int menu_dropdown_panel_example = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int next = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int pause = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int play = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int prev = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int progress_bg_example = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int progress_horizontal_example = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int progress_primary_example = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int progress_secondary_example = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int selectable_background_example = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int speech = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int spinner_ab_default_example = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int spinner_ab_disabled_example = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int spinner_ab_focused_example = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int spinner_ab_pressed_example = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int spinner_background_ab_example = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int SplashScreen = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int tab_indicator_ab_example = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int tab_selected_example = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int tab_selected_focused_example = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int tab_selected_pressed_example = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int tab_unselected_example = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int tab_unselected_focused_example = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int tab_unselected_pressed_example = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int volume = 2130837550;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int messageSpeakNow = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050002
			public const int ActionBar_Solid_Example = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int ActionBar_Transparent_Example = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int ActionBarTabStyle_Example = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int ActionButton_CloseMode_Example = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int DropDownListView_Example = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int DropDownNav_Example = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int PopupMenu_Example = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int ProgressBar_Example = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int Theme_Example_Widget = 2131034122;
			
			// aapt resource value: 0x7f050001
			public const int Theme_Main = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
